name: Check

on:
  schedule:
    - cron: "21 */8 * * *"
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  nightly:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - id: date
      run: echo "::set-output name=version::0.0.1-nightly.$(date -v -1d +%Y%m%d)"
    - name: DRY
      run: "git tag | grep ${{ steps.date.outputs.version }}; test $? -ne 0"
    - run: sh Scripts/pod.sh ${{ steps.date.outputs.version }}
    - name: Create XCFrameworks and Package.swift
      run: sh Scripts/all.sh ${{ steps.date.outputs.version }}
    - name: Commit
      uses: EndBug/add-and-commit@v7
      with:
        add: 'Package.swift'
        message: "add ${{ steps.date.outputs.version }}"
    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ steps.date.outputs.version }}"
        files: 'App/Pods/TensorFlowLiteC/Frameworks/*.zip'

  release:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - id: pod
      run: sh Scripts/pod.sh
    - name: DRY
      run: "git tag | grep ${{ steps.pod.outputs.version }}; test $? -ne 0"
    - name: Create XCFrameworks and Package.swift
      run: sh Scripts/all.sh ${{ steps.pod.outputs.version }}
    - name: Commit
      uses: EndBug/add-and-commit@v7
      with:
        add: 'Package.swift'
        message: "add ${{ steps.pod.outputs.version }}"
    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ steps.pod.outputs.version }}"
        files: 'App/Pods/TensorFlowLiteC/Frameworks/*.zip'
